server:
  port: 20101

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/

spring:
  application:
    name: jec-service-log
  cloud:
    config:
      label: master
      profile: dev
      #uri: http://localhost:30001
      discovery:
        enabled: true
        service-id: jec-config