server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/

spring:
  application:
    name: jec-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/LittlFlowerPig/lfp-jec.git