server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/

spring:
  application:
    name: jec-gateway-config

zuul:
  routes:
    git:
      path: /git/**
      serviceId: jec-config-git