server:
  port: 39999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/

spring:
  application:
    name: jec-config-git
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/LittlFlowerPig/lfp-jec.git